name = "scrum-poker"
main = "workers/src/index.ts"
compatibility_date = "2024-01-01"

# Custom domain configuration
routes = [
  { pattern = "scrum-poker.hyrivera.com", custom_domain = true }
]

[observability.logs]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "RoomObject" ]

[[durable_objects.bindings]]
name = "ROOM_OBJECT"
class_name = "RoomObject"

[[d1_databases]]
binding = "DB"
database_name = "scrum-poker-db"
database_id = "e1f340c1-a93f-40ae-ba96-bfe43cf0cd86"

[vars]
ENVIRONMENT = "development"
VITE_SOCKET_URL = "http://localhost:8787"
NODE_ENV = "development"
DEV = "true"

[env.production]
name = "scrum-poker"

[env.production.vars]
ENVIRONMENT = "production"
VITE_SOCKET_URL = "https://scrum-poker.hyrivera.com"
NODE_ENV = "production"
DEV = "false"

[[env.production.durable_objects.bindings]]
name = "ROOM_OBJECT"
class_name = "RoomObject"

[[env.production.d1_databases]]
binding = "DB"
database_name = "scrum-poker-db"
database_id = "e1f340c1-a93f-40ae-ba96-bfe43cf0cd86"

[env.development]
name = "scrum-poker-dev"

[env.development.vars]
ENVIRONMENT = "development"
VITE_SOCKET_URL = "http://localhost:8787"
NODE_ENV = "development"
DEV = "true" 